import {
  pgTable,
  uuid,
  text,
  boolean,
  integer,
  numeric,
  timestamp,
  index,
} from 'drizzle-orm/pg-core'

/**
 * Correlation Engine results cache (FR14, FR21).
 * Computed nightly by Supabase Edge Function cron job.
 * Previous run's results are soft-replaced (is_active=false) when new run completes.
 *
 * Tier system (architecture §15.2 — Tiered Insights):
 *   gathering    → < 7 days of data: descriptive stats only
 *   provisional  → 7-13 days: preliminary correlations with warning
 *   full         → ≥ 14 days: Pearson/Spearman with confidence intervals
 *
 * Type taxonomy:
 *   positive          → Activity A correlates positively with Area B score
 *   negative          → Activity A correlates negatively with Area B score
 *   neutral           → No significant correlation
 *   destructive_loop  → Pattern where Activity A reduces score that drives Activity A
 *   leverage_point    → Small investment → disproportionate positive impact
 *   bottleneck        → Blocking activity preventing progress in multiple areas
 *
 * Entity references use polymorphic pattern (entity_a_type + entity_a_id)
 * to handle different entity types without multiple FK columns.
 */
export const correlations = pgTable(
  'correlations',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    userId: uuid('user_id').notNull(),
    computedAt: timestamp('computed_at', { withTimezone: true }).notNull(),
    /** Analysis tier based on data availability */
    tier: text('tier').$type<'gathering' | 'provisional' | 'full'>().notNull(),
    /** Correlation type / pattern detected */
    type: text('type')
      .$type<
        'positive' | 'negative' | 'neutral' | 'destructive_loop' | 'leverage_point' | 'bottleneck'
      >()
      .notNull(),
    /** Statistical confidence 0-1 (null for gathering tier) */
    confidence: numeric('confidence', { precision: 4, scale: 3 }),
    /** Entity type for left side: 'area' | 'habit' | 'activity_pattern' | 'project' */
    entityAType: text('entity_a_type').notNull(),
    entityAId: uuid('entity_a_id'),
    /** Entity type for right side */
    entityBType: text('entity_b_type').notNull(),
    entityBId: uuid('entity_b_id'),
    /** Pearson or Spearman coefficient (-1 to 1). null for gathering tier. */
    correlationValue: numeric('correlation_value', { precision: 5, scale: 4 }),
    /** How many data points were used in the analysis */
    dataPointsCount: integer('data_points_count').notNull(),
    /** How many days of data were available */
    daysOfData: integer('days_of_data').notNull(),
    /** Natural language insight generated by ILLMProvider */
    descriptionNl: text('description_nl'),
    /** false = superseded by a newer run. Only is_active=true rows shown in UI. */
    isActive: boolean('is_active').default(true).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    /** UI query: latest active correlations for a user */
    activeUserIdx: index('correlations_user_active_computed_idx').on(
      table.userId,
      table.isActive,
      table.computedAt
    ),
  })
)

export type Correlation = typeof correlations.$inferSelect
export type NewCorrelation = typeof correlations.$inferInsert
