import { pgTable, uuid, text, boolean, integer, timestamp, index } from 'drizzle-orm/pg-core'
import { tasks } from './tasks'
import { areas } from './areas'
import { habits } from './habits'
import { okrs } from './okrs'
import { calendars } from './calendars'

/**
 * UNIFIED Steps + Activities entity (FR5 — Steps = Activities).
 *
 * A "Step" is a planned unit within a Task (task_id is set, planned=true).
 * An "Activity" can be:
 *   - A planned step that was executed (task_id set, planned=true, status='completed')
 *   - A spontaneous activity (task_id=null, planned=false) — always linked to an Area
 *   - A habit occurrence (habit_id set, planned=true)
 *
 * executor_type determines how the step is processed:
 *   human → automatically scheduled in Calendar
 *   ai    → sent to AIOS agent queue automatically
 *   mixed → both human confirmation + AI assistance
 *
 * Note: skill_id tracking is via step_skill_tags junction table (avoids circular FK)
 */
export const stepsActivities = pgTable(
  'steps_activities',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    /** null for spontaneous activities not linked to any workflow task */
    taskId: uuid('task_id').references(() => tasks.id, { onDelete: 'set null' }),
    userId: uuid('user_id').notNull(),
    /** Always required — every activity belongs to an area */
    areaId: uuid('area_id').references(() => areas.id, { onDelete: 'set null' }),
    /** Set if this activity was generated by a habit's rrule */
    habitId: uuid('habit_id').references(() => habits.id, { onDelete: 'set null' }),
    title: text('title').notNull(),
    description: text('description'),
    /** human | ai | mixed */
    executorType: text('executor_type')
      .$type<'human' | 'ai' | 'mixed'>()
      .default('human')
      .notNull(),
    /**
     * true  = planned step from a workflow
     * false = spontaneous activity (no workflow parent)
     */
    planned: boolean('planned').default(true).notNull(),
    /** AIOS agent name when executor_type='ai'. Example: '@dev', '@analyst' */
    aiAgent: text('ai_agent'),
    /** How to verify this step is done. Used by AI to confirm completion. */
    verificationCriteria: text('verification_criteria'),
    status: text('status')
      .$type<'pending' | 'in_progress' | 'completed' | 'skipped' | 'cancelled'>()
      .default('pending')
      .notNull(),
    /** When this step/activity is scheduled to happen */
    scheduledAt: timestamp('scheduled_at', { withTimezone: true }),
    /** Planned duration in minutes */
    scheduledDurationMinutes: integer('scheduled_duration_minutes'),
    /** When the activity was actually completed */
    completedAt: timestamp('completed_at', { withTimezone: true }),
    /**
     * 0-based ordering within the parent task.
     * null for spontaneous activities.
     */
    order: integer('order'),
    /** Optional link to a Key Result — used to auto-calculate KR progress */
    okrId: uuid('okr_id').references(() => okrs.id, { onDelete: 'set null' }),
    /** Calendario personalizado al que pertenece esta actividad (Epic 10) */
    calendarId: uuid('calendar_id').references(() => calendars.id, { onDelete: 'set null' }),
    /**
     * Grupos de actividades recurrentes (Story 10.4).
     * Todas las ocurrencias de un evento recurrente comparten el mismo UUID.
     * null para actividades sin recurrencia.
     */
    recurrenceGroupId: uuid('recurrence_group_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    /** Calendar queries: activities by user + scheduled date range */
    userScheduledIdx: index('steps_activities_user_scheduled_idx').on(
      table.userId,
      table.scheduledAt
    ),
    /** Daily check-in: pending activities for yesterday */
    userStatusIdx: index('steps_activities_user_status_idx').on(table.userId, table.status),
    /** Area health: activities by area + completion */
    areaIdx: index('steps_activities_area_id_idx').on(table.areaId),
    /** Reports: time by calendar */
    calendarIdx: index('steps_activities_calendar_id_idx').on(table.calendarId),
    /** Recurrence group: link all occurrences of a recurring event */
    recurrenceGroupIdx: index('steps_activities_recurrence_group_id_idx').on(
      table.recurrenceGroupId
    ),
  })
)

export type StepActivity = typeof stepsActivities.$inferSelect
export type NewStepActivity = typeof stepsActivities.$inferInsert
