-- ============================================================
-- life-os — Row Level Security Policies
-- Generated by: Dara (@data-engineer)
-- Date: 2026-02-20
-- Applies to: All user-data tables in Supabase PostgreSQL
-- ============================================================
--
-- PATTERN: Every table with user_id uses the KISS RLS policy:
--   SELECT/INSERT/UPDATE/DELETE: user_id = auth.uid()
--
-- EXCEPTIONS:
--   workflow_templates: SELECT open to all authenticated users (system templates)
--   correlations: SELECT/INSERT by user, no UPDATE (immutable results)
--
-- APPLY ORDER: Enable RLS first, then create policies.
-- ============================================================

-- ── HELPER: Updated At trigger function ─────────────────────────────────────

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ── 1. areas ─────────────────────────────────────────────────────────────────

ALTER TABLE areas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "areas: user owns their areas"
  ON areas FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER areas_updated_at
  BEFORE UPDATE ON areas
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── 2. area_scores ───────────────────────────────────────────────────────────

ALTER TABLE area_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "area_scores: user owns their scores"
  ON area_scores FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- No updated_at trigger — area_scores are immutable (append-only)

-- ── 3. okrs ──────────────────────────────────────────────────────────────────

ALTER TABLE okrs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "okrs: user owns their OKRs"
  ON okrs FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER okrs_updated_at
  BEFORE UPDATE ON okrs
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── 4. workflow_templates ────────────────────────────────────────────────────

ALTER TABLE workflow_templates ENABLE ROW LEVEL SECURITY;

-- System templates: all authenticated users can read
CREATE POLICY "workflow_templates: read system templates"
  ON workflow_templates FOR SELECT
  USING (is_system = true AND auth.uid() IS NOT NULL);

-- User-created templates: user owns their own
CREATE POLICY "workflow_templates: user owns custom templates"
  ON workflow_templates FOR ALL
  USING (is_system = false AND user_id = auth.uid())
  WITH CHECK (is_system = false AND user_id = auth.uid());

-- ── 5. projects ──────────────────────────────────────────────────────────────

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "projects: user owns their projects"
  ON projects FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER projects_updated_at
  BEFORE UPDATE ON projects
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── 6. workflows ─────────────────────────────────────────────────────────────

ALTER TABLE workflows ENABLE ROW LEVEL SECURITY;

CREATE POLICY "workflows: user owns their workflows"
  ON workflows FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER workflows_updated_at
  BEFORE UPDATE ON workflows
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── 7. tasks ─────────────────────────────────────────────────────────────────

ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tasks: user owns their tasks"
  ON tasks FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER tasks_updated_at
  BEFORE UPDATE ON tasks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── 8. habits ────────────────────────────────────────────────────────────────

ALTER TABLE habits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "habits: user owns their habits"
  ON habits FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER habits_updated_at
  BEFORE UPDATE ON habits
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── 9. skills ────────────────────────────────────────────────────────────────

ALTER TABLE skills ENABLE ROW LEVEL SECURITY;

CREATE POLICY "skills: user owns their skills"
  ON skills FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER skills_updated_at
  BEFORE UPDATE ON skills
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── 10. steps_activities ─────────────────────────────────────────────────────

ALTER TABLE steps_activities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "steps_activities: user owns their activities"
  ON steps_activities FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER steps_activities_updated_at
  BEFORE UPDATE ON steps_activities
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── 11. time_entries ─────────────────────────────────────────────────────────

ALTER TABLE time_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "time_entries: user owns their time entries"
  ON time_entries FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER time_entries_updated_at
  BEFORE UPDATE ON time_entries
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── 12. inbox_items ──────────────────────────────────────────────────────────

ALTER TABLE inbox_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "inbox_items: user owns their inbox"
  ON inbox_items FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER inbox_items_updated_at
  BEFORE UPDATE ON inbox_items
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── 13. checkin_responses ────────────────────────────────────────────────────

ALTER TABLE checkin_responses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "checkin_responses: user owns their responses"
  ON checkin_responses FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- No updated_at — checkin_responses are immutable (append-only)

-- ── 14. step_skill_tags ──────────────────────────────────────────────────────

ALTER TABLE step_skill_tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "step_skill_tags: user owns their skill tags"
  ON step_skill_tags FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- No updated_at — junction table, append/delete only

-- ── 15. correlations ─────────────────────────────────────────────────────────

ALTER TABLE correlations ENABLE ROW LEVEL SECURITY;

-- SELECT + INSERT only (nightly cron uses service_role for INSERT)
CREATE POLICY "correlations: user can read their correlations"
  ON correlations FOR SELECT
  USING (user_id = auth.uid());

-- Note: INSERT is performed by the Edge Function cron using service_role key.
-- service_role bypasses RLS — no INSERT policy needed for the cron job.
-- If you ever need user-initiated correlation requests, add an INSERT policy.

-- ── FK: auth.users cascade deletes ──────────────────────────────────────────
--
-- Add FK constraints from user_id to auth.users(id) for cascade delete.
-- This ensures all user data is deleted when a user account is deleted.
-- Drizzle does NOT manage cross-schema FKs — add manually here.
--
-- Execute AFTER all tables are created:

ALTER TABLE areas
  ADD CONSTRAINT areas_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE okrs
  ADD CONSTRAINT okrs_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE projects
  ADD CONSTRAINT projects_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE workflows
  ADD CONSTRAINT workflows_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE tasks
  ADD CONSTRAINT tasks_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE habits
  ADD CONSTRAINT habits_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE skills
  ADD CONSTRAINT skills_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE steps_activities
  ADD CONSTRAINT steps_activities_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE time_entries
  ADD CONSTRAINT time_entries_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE inbox_items
  ADD CONSTRAINT inbox_items_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE checkin_responses
  ADD CONSTRAINT checkin_responses_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE step_skill_tags
  ADD CONSTRAINT step_skill_tags_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE correlations
  ADD CONSTRAINT correlations_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE area_scores
  ADD CONSTRAINT area_scores_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- ── Supabase Auth trigger: seed areas on user signup ────────────────────────
--
-- When a new user signs up, automatically create their 8 Maslow areas.
-- Executed via Supabase Auth Hook (Database Webhook on auth.users INSERT).

CREATE OR REPLACE FUNCTION seed_user_areas()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO areas (user_id, maslow_level, "group", name, default_name, weight_multiplier) VALUES
    (NEW.id, 1, 'd_needs', 'Fisiológica',       'Fisiológica',       '2.0'),
    (NEW.id, 2, 'd_needs', 'Seguridad',          'Seguridad',          '2.0'),
    (NEW.id, 3, 'd_needs', 'Conexión Social',    'Conexión Social',    '1.5'),
    (NEW.id, 4, 'd_needs', 'Estima',             'Estima',             '1.5'),
    (NEW.id, 5, 'b_needs', 'Cognitiva',          'Cognitiva',          '1.2'),
    (NEW.id, 6, 'b_needs', 'Estética',           'Estética',           '1.2'),
    (NEW.id, 7, 'b_needs', 'Autorrealización',   'Autorrealización',   '1.0'),
    (NEW.id, 8, 'b_needs', 'Autotrascendencia',  'Autotrascendencia',  '1.0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Register the trigger on auth.users
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION seed_user_areas();

-- ── RLS Audit Query ──────────────────────────────────────────────────────────
-- Run this to verify all tables have RLS enabled:
--
-- SELECT schemaname, tablename, rowsecurity
-- FROM pg_tables
-- WHERE schemaname = 'public'
-- ORDER BY tablename;
--
-- All rows should show rowsecurity = true
