-- ============================================================
-- life-os — Workflow Templates Seed Data (8 MVP templates)
-- Generated by: Dara (@data-engineer)
-- Date: 2026-02-20
-- Apply: After schema migration + RLS policies
-- ============================================================
-- Run as service_role (bypasses RLS for system data seeding)
-- ============================================================

-- Idempotent: safe to run multiple times
-- Uses INSERT ... ON CONFLICT DO NOTHING based on (name, is_system)

INSERT INTO workflow_templates (
  id, name, category, description, executor_type_default, squad_type, is_system, tasks_config
) VALUES

-- 1. Personal Development Sprint
(
  gen_random_uuid(),
  'Personal Development Sprint',
  'personal_development',
  'Estructura para proyectos de desarrollo personal con evaluación, planificación y ejecución.',
  'mixed',
  'coach',
  true,
  '[
    {
      "title": "Diagnóstico Inicial",
      "order": 0,
      "steps": [
        {"title": "Evaluar estado actual del área", "executor_type": "human"},
        {"title": "Analizar fortalezas y brechas con IA", "executor_type": "ai", "ai_agent": "@analyst"},
        {"title": "Definir baseline personal", "executor_type": "human"}
      ]
    },
    {
      "title": "Planificación",
      "order": 1,
      "steps": [
        {"title": "Definir objetivo SMART del sprint", "executor_type": "human"},
        {"title": "Identificar recursos y obstáculos", "executor_type": "mixed"},
        {"title": "Crear plan de acción semanal", "executor_type": "ai", "ai_agent": "@analyst"}
      ]
    },
    {
      "title": "Ejecución",
      "order": 2,
      "steps": [
        {"title": "Actividades diarias del sprint", "executor_type": "human"},
        {"title": "Check-in semanal de progreso", "executor_type": "human"}
      ]
    },
    {
      "title": "Revisión",
      "order": 3,
      "steps": [
        {"title": "Medir resultados vs. objetivo", "executor_type": "mixed"},
        {"title": "Generar informe de aprendizajes con IA", "executor_type": "ai", "ai_agent": "@analyst"},
        {"title": "Decidir continuación o pivote", "executor_type": "human"}
      ]
    }
  ]'
),

-- 2. Product Launch
(
  gen_random_uuid(),
  'Product Launch',
  'product_launch',
  'Pipeline completo de lanzamiento de producto con fases de desarrollo, QA y deployment.',
  'mixed',
  'dev',
  true,
  '[
    {
      "title": "Discovery & Spec",
      "order": 0,
      "steps": [
        {"title": "Definir problema y usuario objetivo", "executor_type": "human"},
        {"title": "Investigar soluciones existentes", "executor_type": "ai", "ai_agent": "@analyst"},
        {"title": "Escribir spec / PRD", "executor_type": "ai", "ai_agent": "@pm"},
        {"title": "Validar spec con stakeholders", "executor_type": "human"}
      ]
    },
    {
      "title": "Arquitectura & Setup",
      "order": 1,
      "steps": [
        {"title": "Diseñar arquitectura técnica", "executor_type": "ai", "ai_agent": "@architect"},
        {"title": "Setup repositorio y CI/CD", "executor_type": "ai", "ai_agent": "@dev"},
        {"title": "Configurar base de datos y auth", "executor_type": "ai", "ai_agent": "@dev"}
      ]
    },
    {
      "title": "Desarrollo MVP",
      "order": 2,
      "steps": [
        {"title": "Implementar features core", "executor_type": "ai", "ai_agent": "@dev"},
        {"title": "Code review y QA", "executor_type": "ai", "ai_agent": "@qa"},
        {"title": "Fix de bugs críticos", "executor_type": "ai", "ai_agent": "@dev"}
      ]
    },
    {
      "title": "Launch",
      "order": 3,
      "steps": [
        {"title": "Deploy a producción", "executor_type": "ai", "ai_agent": "@devops"},
        {"title": "Smoke testing en producción", "executor_type": "human"},
        {"title": "Comunicar lanzamiento", "executor_type": "human"}
      ]
    }
  ]'
),

-- 3. Health Sprint
(
  gen_random_uuid(),
  'Health Sprint',
  'health_sprint',
  'Sprint de 4 semanas para mejorar salud física: sueño, nutrición, ejercicio.',
  'human',
  'coach',
  true,
  '[
    {
      "title": "Baseline Assessment",
      "order": 0,
      "steps": [
        {"title": "Registrar métricas actuales (peso, sueño, energía)", "executor_type": "human"},
        {"title": "Analizar patrones de hábitos con IA", "executor_type": "ai", "ai_agent": "@analyst"},
        {"title": "Definir 3 hábitos objetivo del sprint", "executor_type": "human"}
      ]
    },
    {
      "title": "Semanas 1-2: Fundamentos",
      "order": 1,
      "steps": [
        {"title": "Implementar rutina de sueño", "executor_type": "human"},
        {"title": "Ajustar nutrición básica", "executor_type": "human"},
        {"title": "Iniciar ejercicio 3x semana", "executor_type": "human"}
      ]
    },
    {
      "title": "Semanas 3-4: Consolidación",
      "order": 2,
      "steps": [
        {"title": "Mantener y ajustar rutinas", "executor_type": "human"},
        {"title": "Medir progreso vs. baseline", "executor_type": "mixed"},
        {"title": "Identificar correlaciones con energía", "executor_type": "ai", "ai_agent": "@analyst"}
      ]
    }
  ]'
),

-- 4. Deep Learning
(
  gen_random_uuid(),
  'Deep Learning',
  'learning',
  'Proceso estructurado para aprender una nueva habilidad o tema en profundidad.',
  'mixed',
  'research',
  true,
  '[
    {
      "title": "Mapeo del Territorio",
      "order": 0,
      "steps": [
        {"title": "Definir el alcance de lo que quieres aprender", "executor_type": "human"},
        {"title": "Investigar recursos y roadmap", "executor_type": "ai", "ai_agent": "@analyst"},
        {"title": "Crear mapa mental del tema", "executor_type": "mixed"}
      ]
    },
    {
      "title": "Aprendizaje Activo",
      "order": 1,
      "steps": [
        {"title": "Sesiones de estudio focalizadas (Pomodoro)", "executor_type": "human"},
        {"title": "Tomar notas y síntesis con IA", "executor_type": "ai", "ai_agent": "@analyst"},
        {"title": "Práctica deliberada / ejercicios", "executor_type": "human"}
      ]
    },
    {
      "title": "Consolidación",
      "order": 2,
      "steps": [
        {"title": "Enseñar / explicar el tema (Feynman)", "executor_type": "human"},
        {"title": "Crear proyecto práctico aplicando lo aprendido", "executor_type": "human"},
        {"title": "Documentar aprendizajes clave", "executor_type": "ai", "ai_agent": "@analyst"}
      ]
    }
  ]'
),

-- 5. Content Creation
(
  gen_random_uuid(),
  'Content Creation',
  'content_creation',
  'Pipeline de creación de contenido: ideación, producción, revisión y publicación.',
  'mixed',
  'research',
  true,
  '[
    {
      "title": "Ideación",
      "order": 0,
      "steps": [
        {"title": "Brainstorm de ideas", "executor_type": "human"},
        {"title": "Investigar ángulo y audiencia", "executor_type": "ai", "ai_agent": "@analyst"},
        {"title": "Seleccionar y definir el tema", "executor_type": "human"}
      ]
    },
    {
      "title": "Producción",
      "order": 1,
      "steps": [
        {"title": "Crear outline / estructura", "executor_type": "mixed"},
        {"title": "Escribir borrador", "executor_type": "human"},
        {"title": "Revisión y mejora con IA", "executor_type": "ai", "ai_agent": "@analyst"}
      ]
    },
    {
      "title": "Publicación",
      "order": 2,
      "steps": [
        {"title": "Revisión final y edición", "executor_type": "human"},
        {"title": "Formatear para plataforma", "executor_type": "human"},
        {"title": "Publicar y distribuir", "executor_type": "human"}
      ]
    }
  ]'
),

-- 6. Financial Review
(
  gen_random_uuid(),
  'Financial Review',
  'financial_review',
  'Revisión financiera mensual/trimestral: ingresos, gastos, inversiones y proyecciones.',
  'human',
  'none',
  true,
  '[
    {
      "title": "Recopilación de Datos",
      "order": 0,
      "steps": [
        {"title": "Exportar movimientos bancarios del periodo", "executor_type": "human"},
        {"title": "Categorizar ingresos y gastos", "executor_type": "mixed"},
        {"title": "Verificar estado de inversiones", "executor_type": "human"}
      ]
    },
    {
      "title": "Análisis",
      "order": 1,
      "steps": [
        {"title": "Calcular balance ingresos vs. gastos", "executor_type": "human"},
        {"title": "Identificar patrones y anomalías con IA", "executor_type": "ai", "ai_agent": "@analyst"},
        {"title": "Evaluar progreso hacia metas financieras", "executor_type": "human"}
      ]
    },
    {
      "title": "Planificación",
      "order": 2,
      "steps": [
        {"title": "Ajustar presupuesto próximo periodo", "executor_type": "human"},
        {"title": "Definir acciones de ahorro o inversión", "executor_type": "human"}
      ]
    }
  ]'
),

-- 7. Habit Building
(
  gen_random_uuid(),
  'Habit Building',
  'habit_building',
  'Proceso de 66 días para instalar un nuevo hábito con seguimiento y ajuste.',
  'human',
  'coach',
  true,
  '[
    {
      "title": "Diseño del Hábito",
      "order": 0,
      "steps": [
        {"title": "Definir el hábito y su por qué", "executor_type": "human"},
        {"title": "Identificar cue-routine-reward", "executor_type": "mixed"},
        {"title": "Crear rrule y configurar en el sistema", "executor_type": "human"},
        {"title": "Establecer environment design", "executor_type": "human"}
      ]
    },
    {
      "title": "Días 1-21: Iniciación",
      "order": 1,
      "steps": [
        {"title": "Ejecutar hábito diariamente", "executor_type": "human"},
        {"title": "Daily check-in accountability", "executor_type": "human"},
        {"title": "Revisar streak y ajustar dificultad", "executor_type": "mixed"}
      ]
    },
    {
      "title": "Días 22-66: Consolidación",
      "order": 2,
      "steps": [
        {"title": "Mantener ejecución sin recordatorios externos", "executor_type": "human"},
        {"title": "Análisis de correlaciones con bienestar", "executor_type": "ai", "ai_agent": "@analyst"},
        {"title": "Celebrar milestone de 66 días", "executor_type": "human"}
      ]
    }
  ]'
),

-- 8. Custom (blank template)
(
  gen_random_uuid(),
  'Custom Workflow',
  'custom',
  'Plantilla en blanco para crear workflows personalizados desde cero.',
  'human',
  'none',
  true,
  '[
    {
      "title": "Fase 1",
      "order": 0,
      "steps": [
        {"title": "Primer paso", "executor_type": "human"}
      ]
    }
  ]'
)

ON CONFLICT DO NOTHING;

-- Verify seed:
-- SELECT id, name, category, squad_type FROM workflow_templates ORDER BY category;
